/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "tradex-models-common";

/**
 * alarmListRequest schema
 */
export type AlarmListRequest = BaseRequest & {
  /**
   * next key, to query next (query these alarm has id < lastId)
   */
  lastId?: number | null;
  /**
   * The number of record that user want to see at each page, default 100
   */
  fetchCount?: number | null;
  [k: string]: any;
};
