/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * dashboardImportResponse schema
 */
export interface DashboardImportResponse {
  /**
   * json data of dashboard
   */
  data?: {
    [k: string]: any;
  };
  /**
   * dashboard name
   */
  name?: string;
  /**
   * sharing user name
   */
  sharingUser?: string;
  [k: string]: any;
}
