/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * favoriteListAddRequest schema
 */
export type FavoriteListAddRequest = BaseRequest & {
  /**
   * name of the favorite list
   */
  name: string;
  [k: string]: any;
};
