/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "tradex-models-common";

/**
 * favoriteListDeleteRequest schema
 */
export type FavoriteListDeleteRequest = BaseRequest & {
  /**
   * array of favorite list Ids
   */
  items: number[];
  [k: string]: any;
};
