/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {BaseRequest} from "tradex-models-common";

/**
 * This is a request to update favoriteList
 */
export type FavoriteListUpdateRequest = BaseRequest & {
  items?: {
    /**
     * id of the favorite list
     */
    id: number;
    /**
     * name of the favorite list
     */
    name?: string | null;
    /**
     * order of the favorite list
     */
    order?: number | null;
    /**
     * list of the code in that favorite list
     */
    itemList?: {
      /**
       * is Note or not. If not a note, count as stock
       */
      isNote: boolean;
      /**
       * code, exp: VIC
       */
      data: string;
      [k: string]: any;
    }[];
    [k: string]: any;
  }[];
  [k: string]: any;
};
