/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * notificationUnreadTotalRequest schema
 */
export interface NotificationUnreadTotalRequest {
  /**
   * total remaining unread notification
   */
  totalUnread?: number;
  [k: string]: any;
}
