/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * notificationListResponse schema
 */
export interface NotificationListResponse {
  /**
   * notification id
   */
  id?: number;
  /**
   * type
   */
  type?: string;
  /**
   * method
   */
  method?: string;
  /**
   * username
   */
  username?: string;
  /**
   * account Number
   */
  accountNumber?: string;
  /**
   * sub Number
   */
  subNumber?: string;
  /**
   * channel
   */
  channel?: string;
  /**
   * payload
   */
  payload?: {
    [k: string]: any;
  };
  /**
   * configuration
   */
  configuration?: {
    [k: string]: any;
  };
  /**
   * status, READ or UNREAD
   */
  status?: "READ" | "UNREAD";
  [k: string]: any;
}
