/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * notificationListRequest schema
 */
export type NotificationListRequest = BaseRequest & {
  /**
   * accountNumber
   */
  accountNumber?: string;
  /**
   * subNumber
   */
  subNumber?: string;
  /**
   * id of the last notification that returned in previous request, act as next key
   */
  lastId?: number;
  [k: string]: any;
};
